"""T2: 100条意图分类测试集。每类至少10条, 含歧义与边界。

格式: {question, expected_intent, note}
"""
TESTS = [
    # === Q1 related_party (15条) ===
    {"question": "002594的关联方有哪些", "expected": "Q1", "note": "标准"},
    {"question": "比亚迪的关联方", "expected": "Q1", "note": "简称"},
    {"question": "300750关联方", "expected": "Q1", "note": "无动词"},
    {"question": "茅台的关联方清单", "expected": "Q1", "note": "清单"},
    {"question": "600036关联方有哪些", "expected": "Q1", "note": "标准"},
    {"question": "002594的关联方 只看高置信度的", "expected": "Q1", "note": "带过滤"},
    {"question": "茅台R2规则的关联方", "expected": "Q1", "note": "带规则ID"},
    {"question": "600036的关联方 截至2024年底", "expected": "Q1", "note": "带时点"},
    {"question": "比亚迪有哪些关联人", "expected": "Q1", "note": "关联人"},
    {"question": "300750的关联关系", "expected": "Q1", "note": "关联关系"},
    {"question": "002475关联方", "expected": "Q1", "note": "无动词"},
    {"question": "恒瑞医药的关联交易", "expected": "Q1", "note": "关联交易"},
    {"question": "600519关联方有哪些", "expected": "Q1", "note": "标准"},
    {"question": "000001的关联方清单", "expected": "Q1", "note": "清单"},
    {"question": "隆基绿能的关联方", "expected": "Q1", "note": "简称"},

    # === Q2 relation_path (15条) ===
    {"question": "002594和300750什么关系", "expected": "Q2", "note": "双代码+关系"},
    {"question": "比亚迪和宁德时代有关联吗", "expected": "Q2", "note": "双简称+关联"},
    {"question": "600519和000858的关系路径", "expected": "Q2", "note": "关系路径"},
    {"question": "王传福和融捷投资什么关系", "expected": "Q2", "note": "人+机构"},
    {"question": "比亚迪与宁德时代什么关系", "expected": "Q2", "note": "与"},
    {"question": "002594跟300750有关联吗", "expected": "Q2", "note": "跟"},
    {"question": "600036和000001什么关系", "expected": "Q2", "note": "双代码"},
    {"question": "中国平安和招商银行有关联吗", "expected": "Q2", "note": "双简称"},
    {"question": "茅台和五粮液的关系", "expected": "Q2", "note": "双简称"},
    {"question": "300750与002594的关联", "expected": "Q2", "note": "关联"},
    {"question": "李振国控制的公司跟隆基绿能什么关系", "expected": "Q2", "note": "复杂句"},
    {"question": "000858和600519什么关系", "expected": "Q2", "note": "双代码"},
    {"question": "比亚迪和融捷投资控股集团的关系", "expected": "Q2", "note": "简称+全称"},
    {"question": "002594与600036有关联吗", "expected": "Q2", "note": "双代码+与"},
    {"question": "宁德时代和比亚迪什么关系", "expected": "Q2", "note": "双简称"},

    # === Q3 reverse_control (15条) ===
    {"question": "王传福控制哪些公司", "expected": "Q3", "note": "控制哪些"},
    {"question": "融捷投资持有哪些上市公司", "expected": "Q3", "note": "持有上市"},
    {"question": "曾毓群控制的公司有哪些", "expected": "Q3", "note": "控制的公司"},
    {"question": "中国平安持股超过5%的公司", "expected": "Q3", "note": "持股比例"},
    {"question": "李振国在哪些公司任职", "expected": "Q3", "note": "任职"},
    {"question": "王传福担任哪些公司的董事", "expected": "Q3", "note": "担任"},
    {"question": "吕向阳控制哪些上市公司", "expected": "Q3", "note": "控制上市"},
    {"question": "夏佐全在哪些公司有任职", "expected": "Q3", "note": "任职"},
    {"question": "曾毓群控制了哪些公司", "expected": "Q3", "note": "控制了"},
    {"question": "融捷投资控股集团持有哪些公司", "expected": "Q3", "note": "全称"},
    {"question": "王传福在哪几家公司任职", "expected": "Q3", "note": "哪几家"},
    {"question": "李振国担任什么职务", "expected": "Q3", "note": "担任"},
    {"question": "张炜控制哪些企业", "expected": "Q3", "note": "控制企业"},
    {"question": "曾毓群在哪些上市公司任职", "expected": "Q3", "note": "上市+任职"},
    {"question": "王念强持有哪些公司股份", "expected": "Q3", "note": "持有股份"},

    # === Q4 company_role (15条) ===
    {"question": "002594的前十大股东", "expected": "Q4", "note": "前十大股东"},
    {"question": "比亚迪的实际控制人是谁", "expected": "Q4", "note": "实控人"},
    {"question": "300750的董监高", "expected": "Q4", "note": "董监高"},
    {"question": "茅台的股东", "expected": "Q4", "note": "股东"},
    {"question": "600036的实控人", "expected": "Q4", "note": "实控人"},
    {"question": "比亚迪的董事有哪些", "expected": "Q4", "note": "董事"},
    {"question": "300750的监事", "expected": "Q4", "note": "监事"},
    {"question": "茅台的总经理是谁", "expected": "Q4", "note": "总经理"},
    {"question": "002594的高管", "expected": "Q4", "note": "高管"},
    {"question": "600519的基本信息", "expected": "Q4", "note": "基本信息"},
    {"question": "比亚迪的十大股东", "expected": "Q4", "note": "十大股东"},
    {"question": "宁德时代的实际控制人", "expected": "Q4", "note": "实际控制人"},
    {"question": "000858的股东有哪些", "expected": "Q4", "note": "股东有哪些"},
    {"question": "中国平安的董监高", "expected": "Q4", "note": "董监高"},
    {"question": "招商银行的董事", "expected": "Q4", "note": "董事"},

    # === Q5 risk_events (15条) ===
    {"question": "002594的担保情况", "expected": "Q5", "note": "担保"},
    {"question": "比亚迪的风险事件", "expected": "Q5", "note": "风险事件"},
    {"question": "300750的诉讼", "expected": "Q5", "note": "诉讼"},
    {"question": "茅台有没有质押", "expected": "Q5", "note": "质押"},
    {"question": "600036近三年的担保", "expected": "Q5", "note": "担保+日期"},
    {"question": "比亚迪的担保", "expected": "Q5", "note": "担保"},
    {"question": "002594有哪些诉讼", "expected": "Q5", "note": "诉讼"},
    {"question": "宁德时代的质押情况", "expected": "Q5", "note": "质押"},
    {"question": "600519的法律纠纷", "expected": "Q5", "note": "法律纠纷"},
    {"question": "比亚迪风险事件", "expected": "Q5", "note": "无的"},
    {"question": "002475的担保记录", "expected": "Q5", "note": "担保记录"},
    {"question": "恒瑞医药的诉讼", "expected": "Q5", "note": "诉讼"},
    {"question": "隆基绿能的质押", "expected": "Q5", "note": "质押"},
    {"question": "000001的风险", "expected": "Q5", "note": "风险"},
    {"question": "东方财富有没有担保", "expected": "Q5", "note": "担保疑问"},

    # === Q6 overlap (10条) ===
    {"question": "002594和300750的关联方重合", "expected": "Q6", "note": "重合"},
    {"question": "比亚迪和宁德时代有哪些共同关联方", "expected": "Q6", "note": "共同"},
    {"question": "茅台和五粮液的关联方交集", "expected": "Q6", "note": "交集"},
    {"question": "600036和000001的关联方重叠", "expected": "Q6", "note": "重叠"},
    {"question": "中国平安和招商银行关联方重合度", "expected": "Q6", "note": "重合度"},
    {"question": "002594与300750的关联方重合", "expected": "Q6", "note": "与"},
    {"question": "比亚迪和宁德时代关联方交集", "expected": "Q6", "note": "交集"},
    {"question": "600519和000858的共同关联方", "expected": "Q6", "note": "共同"},
    {"question": "茅台和五粮液关联方重叠", "expected": "Q6", "note": "重叠"},
    {"question": "300750和002594关联方重合", "expected": "Q6", "note": "重合"},

    # === Q7 open (15条) ===
    {"question": "哪些公司的实控人同时控制5家以上上市公司", "expected": "Q7", "note": "模板外"},
    {"question": "比亚迪的关联方里有没有新能源行业的", "expected": "Q7", "note": "模板外"},
    {"question": "持股比例最高的前10个股东", "expected": "Q7", "note": "模板外"},
    {"question": "哪些公司有共同担保", "expected": "Q7", "note": "模板外"},
    {"question": "这个股的后续增长情况", "expected": "Q7", "note": "模板外"},
    {"question": "比亚迪的财务状况怎么样", "expected": "Q7", "note": "模板外"},
    {"question": "宁德时代的估值合理吗", "expected": "Q7", "note": "模板外"},
    {"question": "茅台的利润增长趋势", "expected": "Q7", "note": "模板外"},
    {"question": "002594值得买吗", "expected": "Q7", "note": "模板外"},
    {"question": "新能源行业有哪些关联方密集的公司", "expected": "Q7", "note": "模板外"},
    {"question": "哪家公司的担保金额最高", "expected": "Q7", "note": "模板外"},
    {"question": "比亚迪的竞争对手有哪些", "expected": "Q7", "note": "模板外"},
    {"question": "A股关联方最多的公司是哪家", "expected": "Q7", "note": "模板外"},
    {"question": "002594的市盈率是多少", "expected": "Q7", "note": "模板外"},
    {"question": "宁德时代的股价走势", "expected": "Q7", "note": "模板外"},
]
